name: Github's SuperLinter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint the code
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3.2.0
